<?xml version="1.0" encoding="utf-8"?><Database Name="Jazz" Class="JazzToolDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-R6SSE16\SQLEXPRESS;Initial Catalog=Jazz;Integrated Security=True" SettingsObjectName="JazzDataBase.Properties.Settings" SettingsPropertyName="JazzConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="jazzTool.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="idPosition" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPropTypeBySport" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Position" Member="Position1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Position_PropByPosition" Member="PropByPositions" ThisKey="idPosition" OtherKey="idPosition" Type="PropByPosition" />
      <Association Name="PropTypeBySport_Position" Member="PropTypeBySport" ThisKey="idPropTypeBySport" OtherKey="idPropTypeBySport" Type="PropTypeBySport" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="jazzTool.PropByPosition" Member="PropByPositions">
    <Type Name="PropByPosition">
      <Column Name="idPropByPosition" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idProp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPosition" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[order]" Member="order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Position_PropByPosition" Member="Position" ThisKey="idPosition" OtherKey="idPosition" Type="Position" IsForeignKey="true" />
      <Association Name="Prop_PropByPosition" Member="Prop" ThisKey="idProp" OtherKey="idProp" Type="Prop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="jazzTool.Props" Member="Props">
    <Type Name="Prop">
      <Column Name="idProp" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPropTypeBySport" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AwayTeam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HomeTeam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Prop_PropByPosition" Member="PropByPositions" ThisKey="idProp" OtherKey="idProp" Type="PropByPosition" />
      <Association Name="PropTypeBySport_Prop" Member="PropTypeBySport" ThisKey="idPropTypeBySport" OtherKey="idPropTypeBySport" Type="PropTypeBySport" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="jazzTool.PropType" Member="PropTypes">
    <Type Name="PropType">
      <Column Name="idPropType" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="propType" Member="propType1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="PropType_PropTypeBySport" Member="PropTypeBySports" ThisKey="idPropType" OtherKey="idPropType" Type="PropTypeBySport" />
    </Type>
  </Table>
  <Table Name="jazzTool.PropTypeBySport" Member="PropTypeBySports">
    <Type Name="PropTypeBySport">
      <Column Name="idPropTypeBySport" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idSport" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="idPropType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="PropTypeBySport_Position" Member="Positions" ThisKey="idPropTypeBySport" OtherKey="idPropTypeBySport" Type="Position" />
      <Association Name="PropTypeBySport_Prop" Member="Props" ThisKey="idPropTypeBySport" OtherKey="idPropTypeBySport" Type="Prop" />
      <Association Name="PropType_PropTypeBySport" Member="PropType" ThisKey="idPropType" OtherKey="idPropType" Type="PropType" IsForeignKey="true" />
      <Association Name="sport_PropTypeBySport" Member="sport" ThisKey="idSport" OtherKey="idSport" Type="sport" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="jazzTool.sports" Member="sports">
    <Type Name="sport">
      <Column Name="idSport" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sport" Member="sport1" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lastModificationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lastModificationUser" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="sport_PropTypeBySport" Member="PropTypeBySports" ThisKey="idSport" OtherKey="idSport" Type="PropTypeBySport" />
    </Type>
  </Table>
</Database>